# -*- coding: utf-8 -*-
"""Using the Google Earth Engine API to Acquire Vegetation Index Data for Multiple Time Windows Before a Landslide Occurs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z81vlSDCUWxTuYBqjOayC7lYUoztg0Ql

# Initialize Necessary Python Libraries and Connect to Google Drive and GEE
This script uses the Google Earth Engine API to acquire various vegetation indices for multiple time windows before a landslide event. It is designed for use with standard-format landslide datasets.
"""

# -*- coding: utf-8 -*-
# Import necessary libraries
import ee
import os
import pandas as pd
import numpy as np
from google.colab import auth, drive
import datetime
from tqdm.notebook import tqdm
import time
import warnings
warnings.filterwarnings('ignore')

# Install necessary libraries
!pip install -q earthengine-api tqdm

# Authenticate and initialize Earth Engine
# Initialize Earth Engine and mount Google Drive
def initialize_gee():
    try:
        # Attempt to initialize, specifying your project
        ee.Initialize(project='your_project_name')
        print("Earth Engine has been initialized")
    except Exception as e:
        # If initialization fails, attempt to authenticate
        print(f"Initialization failed, attempting authentication: {str(e)}")
        try:
            # Try different authentication modes
            try:
                # First, try notebook mode
                ee.Authenticate(auth_mode='notebook')
            except:
                # If notebook mode fails, try Colab mode
                try:
                    ee.Authenticate(auth_mode='colab')
                except:
                    # If Colab mode fails, use the default mode
                    ee.Authenticate()

            # Initialize after authentication, ensuring you specify your project
            ee.Initialize(project='your_project_name')
            print("Earth Engine authenticated and initialized successfully")
        except Exception as auth_error:
            print(f"Authentication failed: {str(auth_error)}")
            print("\nAuthentication Troubleshooting Guide:")
            print("1. Ensure your project 'your_project_name' is registered and has the Earth Engine API enabled.")
            print("2. Check that you have sufficient permissions to use the project.")
            print("3. Try executing: earthengine authenticate --auth_mode=notebook")
            print("4. If in Colab, try: ee.Authenticate(auth_mode='colab')")
            raise
# Mount Google Drive
def mount_drive():
    drive.mount('/content/drive')
    print("Google Drive has been mounted")

"""# Define Main Parameters
Please modify the following content according to your actual data and needs.
"""

# Define main parameters
class Config:
    # File paths
    INPUT_FILE = '/content/drive/MyDrive/Codework/Landslide_NDVI/glc_merged_landslide_point.csv'  # Input landslide data
    OUTPUT_DIR = '/content/drive/MyDrive/Codework/Landslide_NDVI/results'  # Output directory
    OUTPUT_FILE = 'landslide_with_vegetation_indices.csv'  # Output filename
    CHECKPOINT_FILE = 'processing_checkpoint.txt'  # Checkpoint file

    # Data column names (adapt to your data format)
    ID_COLUMN = 'OBJECTID'
    DATE_COLUMN = 'Event_Date'
    LAT_COLUMN = 'Latitude'
    LON_COLUMN = 'Longitude'

    # Time window settings (days before the landslide)
    TIME_WINDOWS = [
        (0, 16),     # 0-16 days before
        (16, 32),    # 16-32 days before
        (32, 48),    # 32-48 days before
        (48, 64),    # 48-64 days before
        (64, 80)     # 64-80 days before
    ]

    # Satellite datasets - updated to the latest versions
    MODIS_VI = "MODIS/061/MOD13Q1"       # MODIS Vegetation Indices product (250m, 16-day) - updated version
    MODIS_LAI = "MODIS/061/MOD15A2H"     # MODIS LAI/FPAR product (500m, 8-day)
    SENTINEL_2 = "COPERNICUS/S2_SR_HARMONIZED"  # Sentinel-2 Multispectral data (10-60m) - updated version

    # Vegetation index calculation parameters
    EVI_MIN = 0.1    # Minimum EVI for conversion to FVC
    EVI_MAX = 0.8    # Maximum EVI for conversion to FVC

    # Sleep time after each processing step (in seconds) to avoid API limits
    SLEEP_TIME = 1

# Create a configuration instance
config = Config()

"""# Key Extraction Functions"""

# Ensure the output directory exists
def ensure_output_dir():
    os.makedirs(config.OUTPUT_DIR, exist_ok=True)
    return os.path.join(config.OUTPUT_DIR, config.OUTPUT_FILE)

# Get the checkpoint value
def get_checkpoint():
    checkpoint_path = os.path.join(config.OUTPUT_DIR, config.CHECKPOINT_FILE)
    if os.path.exists(checkpoint_path):
        with open(checkpoint_path, 'r') as f:
            try:
                return int(f.read().strip())
            except:
                return 0
    return 0

# Update the checkpoint
def update_checkpoint(event_id):
    checkpoint_path = os.path.join(config.OUTPUT_DIR, config.CHECKPOINT_FILE)
    with open(checkpoint_path, 'w') as f:
        f.write(str(event_id))

# Calculate Sentinel-2 vegetation indices
def calculate_s2_indices(image):
    try:
        # Extract bands from Sentinel-2
        blue = image.select('B2')
        green = image.select('B3')
        red = image.select('B4')
        nir = image.select('B8')
        swir1 = image.select('B11')
        swir2 = image.select('B12')

        # Calculate NDVI: (NIR - Red) / (NIR + Red)
        ndvi = nir.subtract(red).divide(nir.add(red)).rename('NDVI')

        # Calculate EVI: 2.5 * ((NIR - Red) / (NIR + 6*Red - 7.5*Blue + 1))
        evi = image.expression(
            '2.5 * ((NIR - RED) / (NIR + 6 * RED - 7.5 * BLUE + 1))', {
                'NIR': nir,
                'RED': red,
                'BLUE': blue
            }).rename('EVI')

        # Calculate SAVI: ((NIR - Red) / (NIR + Red + 0.5)) * 1.5
        savi = image.expression(
            '((NIR - RED) / (NIR + RED + 0.5)) * 1.5', {
                'NIR': nir,
                'RED': red
            }).rename('SAVI')

        # Calculate NDMI: (NIR - SWIR1) / (NIR + SWIR1)
        ndmi = nir.subtract(swir1).divide(nir.add(swir1)).rename('NDMI')

        # Calculate NBR: (NIR - SWIR2) / (NIR + SWIR2)
        nbr = nir.subtract(swir2).divide(nir.add(swir2)).rename('NBR')

        # Calculate NDWI (Gao): (NIR - SWIR1) / (NIR + SWIR1) - same as NDMI
        ndwi_gao = nir.subtract(swir1).divide(nir.add(swir1)).rename('NDWI_Gao')

        # Calculate NDWI (McFeeters): (Green - NIR) / (Green + NIR)
        ndwi_mcfeeters = green.subtract(nir).divide(green.add(nir)).rename('NDWI_McFeeters')

        # Calculate PSRI: (Red - Green) / NIR
        psri = red.subtract(green).divide(nir).rename('PSRI')

        # Calculate GNDVI: (NIR - Green) / (NIR + Green)
        gndvi = nir.subtract(green).divide(nir.add(green)).rename('GNDVI')

        # Calculate RVI: NIR / Red
        rvi = nir.divide(red).rename('RVI')

        # Add all indices to the image
        return image.addBands([ndvi, evi, savi, ndmi, nbr, ndwi_gao, ndwi_mcfeeters, psri, gndvi, rvi])
    except Exception as e:
        print(f"Error calculating Sentinel-2 indices: {str(e)}")
        return image  # Return the original image

# Extract vegetation indices from MODIS data
def get_vegetation_indices_for_event(row, config):
    try:
        # Prepare date and location data
        event_date = pd.to_datetime(row[config.DATE_COLUMN]) if pd.notna(row[config.DATE_COLUMN]) else None
        if event_date is None:
            return None

        lat = row[config.LAT_COLUMN]
        lon = row[config.LON_COLUMN]

        # Validate coordinates
        if not (-90 <= lat <= 90) or not (-180 <= lon <= 180):
            print(f"Invalid coordinates: Lat={lat}, Lon={lon}")
            return None

        # Convert to ee format
        ee_date = ee.Date(event_date.strftime('%Y-%m-%d'))
        point = ee.Geometry.Point([lon, lat])

        # Initialize results dictionary
        result = {
            config.ID_COLUMN: row[config.ID_COLUMN],
            'Event_Date': event_date,
            'Latitude': lat,
            'Longitude': lon
        }

        # Add other columns from the original data
        for col in row.index:
            if col not in [config.ID_COLUMN, config.DATE_COLUMN, config.LAT_COLUMN, config.LON_COLUMN]:
                result[col] = row[col]

        # Get data for each time window
        for i, (end_days, start_days) in enumerate(config.TIME_WINDOWS, 1):
            window_start = ee_date.advance(-start_days, 'day')
            window_end = ee_date.advance(-end_days, 'day')

            # ---------------------------- MODIS VI Data ----------------------------
            try:
                filtered_vi = ee.ImageCollection(config.MODIS_VI) \
                                .filterDate(window_start, window_end) \
                                .filterBounds(point) \
                                .sort('system:time_start', False)

                # Get the latest image
                first_vi = filtered_vi.first()

                # Initialize VI data for this window
                window_vi = {
                    f'Window_{i}_Start_Days': start_days,
                    f'Window_{i}_End_Days': end_days,
                    f'MODIS_Date_{i}': None,
                    f'Days_Before_{i}': None,
                    f'NDVI_{i}': None,
                    f'EVI_{i}': None,
                    f'FVC_{i}': None,
                    f'QA_{i}': None
                }

                # If data is available, extract values
                if first_vi is not None:
                    image_vi = ee.Image(first_vi)

                    # Get date information
                    image_date = ee.Date(image_vi.get('system:time_start')).format('YYYY-MM-dd').getInfo()
                    window_vi[f'MODIS_Date_{i}'] = image_date

                    # Calculate days before the event
                    days_before = ee.Number(ee_date.difference(ee.Date(image_vi.get('system:time_start')), 'day')).getInfo()
                    window_vi[f'Days_Before_{i}'] = days_before

                    # Extract NDVI, EVI, and QA data
                    vi_data = image_vi.select(['NDVI', 'EVI', 'SummaryQA']).reduceRegion(
                        reducer=ee.Reducer.first(),
                        geometry=point,
                        scale=250
                    ).getInfo()

                    # Process NDVI (scale factor 0.0001)
                    ndvi = vi_data.get('NDVI')
                    if ndvi is not None:
                        window_vi[f'NDVI_{i}'] = ndvi * 0.0001

                    # Process EVI and calculate FVC (scale factor 0.0001)
                    evi = vi_data.get('EVI')
                    if evi is not None:
                        evi_scaled = evi * 0.0001
                        window_vi[f'EVI_{i}'] = evi_scaled

                        # Calculate Fractional Vegetation Cover (FVC)
                        try:
                            if evi_scaled >= config.EVI_MIN:  # Avoid negative values in the denominator
                                fvc = (evi_scaled - config.EVI_MIN) / (config.EVI_MAX - config.EVI_MIN)
                                window_vi[f'FVC_{i}'] = max(0, min(1, fvc))  # Constrain to 0-1 range
                        except:
                            window_vi[f'FVC_{i}'] = None

                    # Extract QA data
                    qa = vi_data.get('SummaryQA')
                    if qa is not None:
                        window_vi[f'QA_{i}'] = qa
            except Exception as e:
                print(f"Error processing MODIS VI data: {str(e)}")

            # ---------------------------- MODIS LAI Data ----------------------------
            try:
                filtered_lai = ee.ImageCollection(config.MODIS_LAI) \
                                .filterDate(window_start, window_end) \
                                .filterBounds(point) \
                                .sort('system:time_start', False)

                # Get the latest image
                first_lai = filtered_lai.first()

                # Initialize LAI data for this window
                window_lai = {
                    f'LAI_Date_{i}': None,
                    f'LAI_{i}': None,
                    f'FPAR_{i}': None
                }

                # If data is available, extract values
                if first_lai is not None:
                    image_lai = ee.Image(first_lai)

                    # Get date information
                    image_date = ee.Date(image_lai.get('system:time_start')).format('YYYY-MM-dd').getInfo()
                    window_lai[f'LAI_Date_{i}'] = image_date

                    # Extract LAI and FPAR data
                    lai_data = image_lai.select(['Lai_500m', 'Fpar_500m']).reduceRegion(
                        reducer=ee.Reducer.first(),
                        geometry=point,
                        scale=500
                    ).getInfo()

                    # Process LAI (scale factor 0.1)
                    lai = lai_data.get('Lai_500m')
                    if lai is not None:
                        window_lai[f'LAI_{i}'] = lai * 0.1

                    # Process FPAR (scale factor 0.01)
                    fpar = lai_data.get('Fpar_500m')
                    if fpar is not None:
                        window_lai[f'FPAR_{i}'] = fpar * 0.01
            except Exception as e:
                print(f"Error processing MODIS LAI data: {str(e)}")

            # ---------------------------- Sentinel-2 Data ----------------------------
            # Note: Sentinel-2 data is available from late 2015 onwards, will return None for earlier data
            # Modified Sentinel-2 data processing section
            try:
                # Use data with low cloud cover
                filtered_s2 = ee.ImageCollection(config.SENTINEL_2) \
                                .filterDate(window_start, window_end) \
                                .filterBounds(point) \
                                .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', 30)) \
                                .sort('system:time_start', False)

                # Get the collection size
                collection_size = filtered_s2.size().getInfo()

                # Initialize Sentinel-2 index data for this window
                window_s2 = {
                    f'S2_Date_{i}': None,
                    f'S2_NDVI_{i}': None,
                    f'S2_EVI_{i}': None,
                    f'S2_SAVI_{i}': None,
                    f'S2_NDMI_{i}': None,
                    f'S2_NBR_{i}': None,
                    f'S2_NDWI_Gao_{i}': None,
                    f'S2_NDWI_McFeeters_{i}': None,
                    f'S2_PSRI_{i}': None,
                    f'S2_GNDVI_{i}': None,
                    f'S2_RVI_{i}': None
                }

                # Only proceed if the collection has images
                if collection_size > 0:
                    # Get the first image
                    first_s2 = filtered_s2.first()

                    # Explicitly check if the first image is not null
                    if first_s2 is not None:
                        image_s2 = ee.Image(first_s2)

                        # Check if the image is valid
                        image_id = image_s2.get('system:id').getInfo()

                        if image_id is not None:
                            # Get date information
                            image_date = ee.Date(image_s2.get('system:time_start')).format('YYYY-MM-dd').getInfo()
                            window_s2[f'S2_Date_{i}'] = image_date

                            # Get the list of band names
                            band_names = image_s2.bandNames().getInfo()

                            # Check for necessary bands to calculate vegetation indices
                            required_bands = ['B2', 'B3', 'B4', 'B8', 'B11', 'B12']
                            missing_bands = [band for band in required_bands if band not in band_names]

                            if not missing_bands:  # All necessary bands are present
                                # Calculate all vegetation indices
                                indices_image = calculate_s2_indices(image_s2)

                                # Extract all index values
                                indices_data = indices_image.select([
                                    'NDVI', 'EVI', 'SAVI', 'NDMI', 'NBR',
                                    'NDWI_Gao', 'NDWI_McFeeters', 'PSRI', 'GNDVI', 'RVI'
                                ]).reduceRegion(
                                    reducer=ee.Reducer.first(),
                                    geometry=point,
                                    scale=10  # Sentinel-2's highest resolution is 10m
                                ).getInfo()

                                # Save individual index values
                                window_s2[f'S2_NDVI_{i}'] = indices_data.get('NDVI')
                                window_s2[f'S2_EVI_{i}'] = indices_data.get('EVI')
                                window_s2[f'S2_SAVI_{i}'] = indices_data.get('SAVI')
                                window_s2[f'S2_NDMI_{i}'] = indices_data.get('NDMI')
                                window_s2[f'S2_NBR_{i}'] = indices_data.get('NBR')
                                window_s2[f'S2_NDWI_Gao_{i}'] = indices_data.get('NDWI_Gao')
                                window_s2[f'S2_NDWI_McFeeters_{i}'] = indices_data.get('NDWI_McFeeters')
                                window_s2[f'S2_PSRI_{i}'] = indices_data.get('PSRI')
                                window_s2[f'S2_GNDVI_{i}'] = indices_data.get('GNDVI')
                                window_s2[f'S2_RVI_{i}'] = indices_data.get('RVI')
                            else:
                                print(f"Missing bands required for vegetation index calculation: {', '.join(missing_bands)}")
                        else:
                            print(f"Could not get Sentinel-2 image ID, possibly an invalid image")
                    else:
                        print(f"First image in Sentinel-2 collection is null")
                else:
                    print(f"No qualifying Sentinel-2 images found in the specified time range")

            except Exception as e:
                print(f"Error processing Sentinel-2 image: {str(e)}")
                # Log more detailed error information
                import traceback
                print(traceback.format_exc())

            # Update results dictionary
            result.update(window_vi)
            result.update(window_lai)
            result.update(window_s2)

        return result

    except Exception as e:
        print(f"Error processing ID {row.get(config.ID_COLUMN, 'unknown')}: {str(e)}")
        return None

# Data cleaning function
def clean_data(df):
    print("Performing data cleaning...")

    # 1. Remove rows with no vegetation index data across all time windows
    total_indices = 0
    for i in range(1, 6):  # Assuming 5 time windows
        # Check if at least one vegetation index exists for each window
        has_index = False
        for index_col in ['NDVI', 'EVI', 'LAI', 'S2_NDVI']:
            col_name = f'{index_col}_{i}'
            if col_name in df.columns:
                total_indices += 1
                if df[col_name].notna().any():
                    has_index = True
                    break

        if has_index:
            df[f'has_index_{i}'] = True
        else:
            df[f'has_index_{i}'] = False

    # Keep only rows with data in at least one window
    rows_before = len(df)
    has_any_index = df[[f'has_index_{i}' for i in range(1, 6)]].any(axis=1)
    df = df[has_any_index]
    rows_after = len(df)
    print(f"Removed {rows_before - rows_after} records with no vegetation index data")

    # Remove helper columns
    for i in range(1, 6):
        if f'has_index_{i}' in df.columns:
            df = df.drop(columns=[f'has_index_{i}'])

    # 2. Clean data based on the Quality Assessment (QA) field
    qa_cols = [col for col in df.columns if col.startswith('QA_')]
    if qa_cols:
        rows_before = len(df)
        for qa_col in qa_cols:
            # MODIS quality values: 0=good, 1=marginal, 2=cloudy, 3=unprocessed
            # Keep only data with good (0) or marginal (1) quality
            idx = qa_col.split('_')[1]  # Extract window index
            index_cols = [f'NDVI_{idx}', f'EVI_{idx}', f'FVC_{idx}']

            # If QA > 1, set the corresponding indices to NaN
            bad_quality = df[qa_col] > 1
            if bad_quality.any():
                for col in index_cols:
                    if col in df.columns:
                        df.loc[bad_quality, col] = np.nan

                print(f"Based on QA, marked {bad_quality.sum()} rows in window {idx} as NaN")

    # 3. Check for data outliers
    for col in df.columns:
        if not df[col].dtype in [np.float64, np.int64]:
            continue  # Skip non-numeric columns

        if col.startswith(('NDVI_', 'S2_NDVI_')):
            # NDVI is typically in the range -1 to 1
            if df[col].min() < -1 or df[col].max() > 1:
                print(f"Warning: {col} has out-of-range values")
                df[col] = df[col].clip(-1, 1)

        elif col.startswith('EVI_') or col.startswith('S2_EVI_'):
            # EVI is typically in the range -1 to 1, but can theoretically exceed 1
            if df[col].min() < -1 or df[col].max() > 2:
                print(f"Warning: {col} has out-of-range values")
                df[col] = df[col].clip(-1, 2)

        elif col.startswith('FVC_'):
            # FVC should be in the range 0 to 1
            if df[col].min() < 0 or df[col].max() > 1:
                print(f"Warning: {col} has out-of-range values")
                df[col] = df[col].clip(0, 1)

        elif col.startswith('LAI_'):
            # LAI is typically in the range 0 to 10
            if df[col].min() < 0 or df[col].max() > 10:
                print(f"Warning: {col} has out-of-range values")
                df[col] = df[col].clip(0, 10)

    # 4. Calculate the rate of change for vegetation indices
    print("Calculating rate of change for vegetation indices...")
    for index in ['NDVI', 'EVI', 'LAI', 'S2_NDVI']:
        for i in range(1, 5):  # Calculate change between adjacent windows
            col1 = f'{index}_{i}'
            col2 = f'{index}_{i+1}'
            change_col = f'{index}_change_{i}_to_{i+1}'

            if col1 in df.columns and col2 in df.columns:
                # Handle division by zero
                with np.errstate(divide='ignore', invalid='ignore'):
                    change = (df[col2] - df[col1]) / df[col1]
                    # Handle infinite values or NaN
                    df[change_col] = np.where(np.isfinite(change), change, np.nan)

    # 5. Generate a statistical summary
    print("\nData Statistical Summary:")
    summary = {}

    # Count how much valid data exists for each time window
    for i in range(1, 6):
        valid_count = 0
        for index in ['NDVI', 'EVI', 'LAI', 'S2_NDVI']:
            col = f'{index}_{i}'
            if col in df.columns:
                valid_count += df[col].notna().sum()

        summary[f'Window_{i}_valid_data'] = valid_count

    for key, value in summary.items():
        print(f"{key}: {value}")

    return df

# Main processing function
def process_landslide_data():
    # Initialize Earth Engine and mount Google Drive
    initialize_gee()
    mount_drive()

    # Ensure the output directory exists
    output_path = ensure_output_dir()

    # Read landslide data
    try:
        landslides = pd.read_csv(config.INPUT_FILE)
        print(f"Successfully read {len(landslides)} landslide records")

        # Ensure the date column is in datetime format
        landslides[config.DATE_COLUMN] = pd.to_datetime(landslides[config.DATE_COLUMN], errors='coerce')

        # Remove records with no date
        landslides_with_dates = landslides.dropna(subset=[config.DATE_COLUMN])
        if len(landslides) > len(landslides_with_dates):
            print(f"Warning: Removed {len(landslides) - len(landslides_with_dates)} records with no valid date")
            landslides = landslides_with_dates
    except Exception as e:
        print(f"Error reading landslide data: {str(e)}")
        return

    # Get the ID of the last processed record
    last_processed_id = get_checkpoint()
    print(f"Starting processing from ID {last_processed_id}")

    # Filter for unprocessed data
    landslides_to_process = landslides[landslides[config.ID_COLUMN] > last_processed_id]

    if len(landslides_to_process) == 0:
        print("No new data to process")
        return

    print(f"Need to process {len(landslides_to_process)} records")

    # Process each landslide record
    results = []
    error_count = 0

    for idx, row in tqdm(landslides_to_process.iterrows(), total=len(landslides_to_process), desc="Processing landslide data"):
        try:
            result = get_vegetation_indices_for_event(row, config)

            if result is not None:
                # Add to the results list
                results.append(result)

                # Update the checkpoint
                update_checkpoint(row[config.ID_COLUMN])

                # Periodically save results
                if len(results) % 10 == 0:
                    temp_df = pd.DataFrame(results)
                    temp_df.to_csv(output_path, mode='a', header=not os.path.exists(output_path), index=False)
                    results = []  # Clear saved results
                    print(f"Saved intermediate results, currently at ID: {row[config.ID_COLUMN]}")

        except Exception as e:
            print(f"Error processing ID {row[config.ID_COLUMN]}: {str(e)}")
            error_count += 1

            # If there are too many errors, it might be an API issue, so pause
            if error_count > 5:
                print("Too many errors, pausing for 30 seconds...")
                time.sleep(30)
                error_count = 0

        # Short sleep to avoid API limits
        time.sleep(config.SLEEP_TIME)

    # Save remaining results
    if results:
        temp_df = pd.DataFrame(results)
        temp_df.to_csv(output_path, mode='a', header=not os.path.exists(output_path), index=False)
        print(f"Saved final results, {len(results)} records in total")

    # Read the complete results and perform data cleaning
    if os.path.exists(output_path):
        try:
            full_df = pd.read_csv(output_path)
            print(f"Successfully read {len(full_df)} records for data cleaning")

            # Clean the data
            cleaned_df = clean_data(full_df)

            # Save the cleaned data
            cleaned_output_path = os.path.join(config.OUTPUT_DIR, 'cleaned_' + config.OUTPUT_FILE)
            cleaned_df.to_csv(cleaned_output_path, index=False)
            print(f"Data cleaning complete, {len(cleaned_df)} records after cleaning")
            print(f"Cleaned data saved to: {cleaned_output_path}")

            # Display data statistics
            print("\nData Statistics:")
            print(f"Total records: {len(cleaned_df)}")
            for i in range(1, 6):  # Assuming 5 time windows
                for index in ['NDVI', 'EVI', 'LAI', 'FPAR']:
                    col = f'{index}_{i}'
                    if col in cleaned_df.columns:
                        valid_count = cleaned_df[col].notna().sum()
                        valid_percent = (valid_count / len(cleaned_df)) * 100
                        print(f"{col}: {valid_count} valid values ({valid_percent:.1f}%)")

            return cleaned_df

        except Exception as e:
            print(f"Error during data cleaning process: {str(e)}")
    else:
        print("No data file found to clean")

"""# Run the Main Function"""

if __name__ == "__main__":
    cleaned_data = process_landslide_data()