# -*- coding: utf-8 -*-
"""Landslide Point Land Cover and Forest Data Extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F6bgOxBy9t_46ekuPhFnx6D9kxLGgmWD
"""

# -*- coding: utf-8 -*-
"""
Landslide Point Land Cover and Forest Data Extraction Tool

This script extracts land cover type and forest characteristic data for landslide points from multiple data sources.
It automatically selects the closest time-series data based on the landslide event date.

Data sources include:
1. ESA WorldCover (10m, 2020+)
2. MODIS Land Cover (500m, 2001-2020+)
3. Copernicus Global Land Cover (100m, 2015-2020+)
4. NASA GFCC (30m, 2000/2005/2010/2015)
5. Hansen Global Forest Change (30m, 2000-2020+)
6. JAXA ALOS PALSAR Forest/Non-Forest (25m, 2007-2020)
7. Dynamic World (10m, 2015-2020+)
"""

# Import necessary libraries
import ee
import os
import pandas as pd
import numpy as np
from google.colab import auth, drive
import datetime
from tqdm.notebook import tqdm
import time
import warnings
warnings.filterwarnings('ignore')

# Install necessary libraries
!pip install -q earthengine-api tqdm

# Initialize Earth Engine and mount Google Drive
def initialize_gee():
    try:
        # Attempt to initialize, specifying your project
        ee.Initialize(project='your_project_name')  # Replace with your project ID
        print("Earth Engine has been initialized")
    except Exception as e:
        # If initialization fails, attempt to authenticate
        print(f"Initialization failed, attempting authentication: {str(e)}")
        try:
            # Try different authentication modes
            try:
                # First, try notebook mode
                ee.Authenticate(auth_mode='notebook')
            except:
                # If notebook mode fails, try Colab mode
                try:
                    ee.Authenticate(auth_mode='colab')
                except:
                    # If Colab mode fails, use the default mode
                    ee.Authenticate()

            # Initialize after authentication, ensuring you specify your project
            ee.Initialize(project='your_project_name')  # Replace with your project ID
            print("Earth Engine authenticated and initialized successfully")
        except Exception as auth_error:
            print(f"Authentication failed: {str(auth_error)}")
            print("\nAuthentication Troubleshooting Guide:")
            print("1. Ensure your project is registered and has the Earth Engine API enabled.")
            print("2. Check that you have sufficient permissions to use the project.")
            print("3. Try executing: earthengine authenticate --auth_mode=notebook")
            print("4. If in Colab, try: ee.Authenticate(auth_mode='colab')")
            raise

# Mount Google Drive
def mount_drive():
    drive.mount('/content/drive')
    print("Google Drive has been mounted")

# Define the configuration class
class Config:
    # File paths
    INPUT_FILE = '/content/drive/MyDrive/Codework/Landslide_NDVI/glc_merged_landslide_point.csv'  # Input landslide data
    OUTPUT_DIR = '/content/drive/MyDrive/Codework/Landslide_NDVI/results'  # Output directory
    OUTPUT_FILE = 'landslide_landcover_forest_data.csv'  # Output filename
    CHECKPOINT_FILE = 'landcover_processing_checkpoint.txt'  # Checkpoint file

    # Data column names (adapt to your data format)
    ID_COLUMN = 'OBJECTID'
    DATE_COLUMN = 'Event_Date'
    LAT_COLUMN = 'Latitude'
    LON_COLUMN = 'Longitude'

    # Buffer size (in meters) - can be used to create a statistical area around the landslide point
    BUFFER_SIZE = 90  # Default is 90 meters, approximately 3 30m pixels

    # Sleep time after each processing step (in seconds) to avoid API limits
    SLEEP_TIME = 1

# Create a configuration instance
config = Config()

# Ensure the output directory exists
def ensure_output_dir():
    os.makedirs(config.OUTPUT_DIR, exist_ok=True)
    return os.path.join(config.OUTPUT_DIR, config.OUTPUT_FILE)

# Get the checkpoint value
def get_checkpoint():
    checkpoint_path = os.path.join(config.OUTPUT_DIR, config.CHECKPOINT_FILE)
    if os.path.exists(checkpoint_path):
        with open(checkpoint_path, 'r') as f:
            try:
                return int(f.read().strip())
            except:
                return 0
    return 0

# Update the checkpoint
def update_checkpoint(event_id):
    checkpoint_path = os.path.join(config.OUTPUT_DIR, config.CHECKPOINT_FILE)
    with open(checkpoint_path, 'w') as f:
        f.write(str(event_id))

# Create a buffered point
def create_buffered_point(lon, lat, buffer_size=None):
    """Creates a point with an optional buffer"""
    point = ee.Geometry.Point([lon, lat])
    if buffer_size:
        return point.buffer(buffer_size)
    return point

# 1. ESA WorldCover (10m, 2020-present)
def get_esa_worldcover(geometry, year):
    """
    Get ESA WorldCover land cover data.
    Available years: 2020-present
    Resolution: 10m
    """
    result = {
        'ESA_WorldCover': None,
        'ESA_WorldCover_Class': None
    }

    # WorldCover class mapping
    worldcover_classes = {
        10: 'Tree cover',
        20: 'Shrubland',
        30: 'Grassland',
        40: 'Cropland',
        50: 'Built-up',
        60: 'Bare / sparse vegetation',
        70: 'Snow and ice',
        80: 'Permanent water bodies',
        90: 'Herbaceous wetland',
        95: 'Mangroves',
        100: 'Moss and lichen'
    }

    try:
        # Only applicable for data from 2020 onwards
        if year < 2020:
            return result

        # Currently only the 2020 version is available
        worldcover = ee.Image('ESA/WorldCover/v200')

        # Reduce region to get the first value
        worldcover_value = worldcover.reduceRegion(
            reducer=ee.Reducer.mode(),  # Use mode to get the most common class
            geometry=geometry,
            scale=10
        ).get('Map').getInfo()

        if worldcover_value is not None:
            result['ESA_WorldCover'] = worldcover_value
            result['ESA_WorldCover_Class'] = worldcover_classes.get(worldcover_value, 'Unknown')
            result['ESA_WorldCover_Year'] = 2020  # Data year
    except Exception as e:
        print(f"Error getting ESA WorldCover data: {str(e)}")

    return result

# 2. MODIS Land Cover (500m, 2001-present)
def get_modis_landcover(geometry, year):
    """
    Get MODIS land cover data.
    Available years: 2001-present
    Resolution: 500m
    """
    result = {
        'MODIS_IGBP': None,
        'MODIS_IGBP_Class': None,
        'MODIS_LC_Year': None
    }

    # IGBP class mapping
    igbp_classes = {
        1: 'Evergreen Needleleaf Forests',
        2: 'Evergreen Broadleaf Forests',
        3: 'Deciduous Needleleaf Forests',
        4: 'Deciduous Broadleaf Forests',
        5: 'Mixed Forests',
        6: 'Closed Shrublands',
        7: 'Open Shrublands',
        8: 'Woody Savannas',
        9: 'Savannas',
        10: 'Grasslands',
        11: 'Permanent Wetlands',
        12: 'Croplands',
        13: 'Urban and Built-up Lands',
        14: 'Cropland/Natural Vegetation Mosaics',
        15: 'Snow and Ice',
        16: 'Barren',
        17: 'Water Bodies'
    }

    try:
        # Ensure the year is within the MODIS data range (2001-present)
        if year < 2001:
            return result

        # Select the nearest available year, assuming data is up to 2023
        valid_year = min(year, 2023)

        # Build the date range
        start_date = ee.Date.fromYMD(valid_year, 1, 1)
        end_date = ee.Date.fromYMD(valid_year, 12, 31)

        # Get MODIS land cover data
        modis_lc = ee.ImageCollection('MODIS/006/MCD12Q1') \
            .filterDate(start_date, end_date) \
            .first()

        if modis_lc is not None:
            # IGBP classification (LC_Type1)
            igbp_value = modis_lc.select('LC_Type1').reduceRegion(
                reducer=ee.Reducer.mode(),
                geometry=geometry,
                scale=500
            ).get('LC_Type1').getInfo()

            if igbp_value is not None:
                result['MODIS_IGBP'] = igbp_value
                result['MODIS_IGBP_Class'] = igbp_classes.get(igbp_value, 'Unknown')
                result['MODIS_LC_Year'] = valid_year
    except Exception as e:
        print(f"Error getting MODIS land cover data: {str(e)}")

    return result

# 3. Copernicus Global Land Cover (100m, 2015-present)
def get_copernicus_landcover(geometry, year):
    """
    Get Copernicus Global Land Cover data.
    Available years: 2015-present
    Resolution: 100m
    """
    result = {
        'Copernicus_LC': None,
        'Copernicus_LC_Class': None,
        'Copernicus_LC_Year': None,
        'Tree_Cover_Fraction': None,
        'Forest_Type': None
    }

    # Copernicus class mapping (simplified version)
    copernicus_classes = {
        111: 'Closed forest, evergreen needle leaf',
        112: 'Closed forest, evergreen broad leaf',
        113: 'Closed forest, deciduous needle leaf',
        114: 'Closed forest, deciduous broad leaf',
        115: 'Closed forest, mixed',
        116: 'Closed forest, unknown',
        121: 'Open forest, evergreen needle leaf',
        122: 'Open forest, evergreen broad leaf',
        123: 'Open forest, deciduous needle leaf',
        124: 'Open forest, deciduous broad leaf',
        125: 'Open forest, mixed',
        126: 'Open forest, unknown',
        20: 'Shrubs',
        30: 'Herbaceous vegetation',
        40: 'Cropland',
        50: 'Urban / built up',
        60: 'Bare / sparse vegetation',
        70: 'Snow and ice',
        80: 'Permanent water bodies',
        90: 'Herbaceous wetland',
        100: 'Moss and lichen'
    }

    forest_types = {
        0: 'Unknown',
        1: 'Evergreen needle leaf',
        2: 'Evergreen broad leaf',
        3: 'Deciduous needle leaf',
        4: 'Deciduous broad leaf',
        5: 'Mixed forest'
    }

    try:
        # Ensure the year is within the Copernicus data range (2015-present)
        if year < 2015:
            return result

        # Select the nearest available year, assuming data is up to 2022
        valid_year = min(year, 2022)

        # Build the dataset ID
        dataset_id = f'COPERNICUS/Landcover/100m/Proba-V-C3/Global/{valid_year}'

        copernicus_lc = ee.Image(dataset_id)

        # Extract discrete land cover class
        discrete_class = copernicus_lc.select('discrete_classification').reduceRegion(
            reducer=ee.Reducer.mode(),
            geometry=geometry,
            scale=100
        ).get('discrete_classification').getInfo()

        if discrete_class is not None:
            result['Copernicus_LC'] = discrete_class
            result['Copernicus_LC_Class'] = copernicus_classes.get(discrete_class, 'Unknown')
            result['Copernicus_LC_Year'] = valid_year

        # Extract forest type proportion
        forest_data = copernicus_lc.select(['tree-coverfraction', 'forest_type']).reduceRegion(
            reducer=ee.Reducer.mean(),
            geometry=geometry,
            scale=100
        ).getInfo()

        result['Tree_Cover_Fraction'] = forest_data.get('tree-coverfraction')

        forest_type_value = forest_data.get('forest_type')
        if forest_type_value is not None:
            result['Forest_Type'] = forest_types.get(int(forest_type_value), 'Unknown')
    except Exception as e:
        print(f"Error getting Copernicus land cover data: {str(e)}")

    return result

# 4. NASA GFCC (30m, 2000/2005/2010/2015)
def get_nasa_gfcc(geometry, year):
    """
    Get NASA Global Forest Cover Change data.
    Available years: 2000, 2005, 2010, 2015
    Resolution: 30m
    """
    result = {
        'NASA_GFCC_Year': None,
        'Tree_Canopy_Cover_Percent': None,
        'Forest_Density_Class': None,
        'Tree_Height_Meters': None,
        'Tree_Height_Class': None,
        'Tree_Cover_Change_Percent': None,
        'Forest_Change_Class': None
    }

    try:
        # Select the closest GFCC year (2000, 2005, 2010, 2015)
        if year < 2003:
            gfcc_year = 2000
        elif year < 2008:
            gfcc_year = 2005
        elif year < 2013:
            gfcc_year = 2010
        else:
            gfcc_year = 2015

        result['NASA_GFCC_Year'] = gfcc_year

        # Build dataset name
        gfcc_tc_dataset = f'NASA/MEASURES/GFCC/TC/v3/{gfcc_year}'

        # 1. Extract tree canopy cover data
        try:
            tree_cover = ee.Image(gfcc_tc_dataset)
            tc_data = tree_cover.select('tree_canopy_cover').reduceRegion(
                reducer=ee.Reducer.mean(),
                geometry=geometry,
                scale=30
            ).get('tree_canopy_cover').getInfo()

            result['Tree_Canopy_Cover_Percent'] = tc_data

            # Add forest cover class (based on cover percentage)
            if tc_data is not None:
                if tc_data < 10:
                    forest_class = 'Non-forest'
                elif tc_data < 30:
                    forest_class = 'Sparse forest'
                elif tc_data < 60:
                    forest_class = 'Moderate forest'
                else:
                    forest_class = 'Dense forest'

                result['Forest_Density_Class'] = forest_class
        except Exception as e:
            print(f"Error getting tree canopy cover: {str(e)}")

        # 2. Attempt to extract tree height data (may not be available for all areas and years)
        try:
            tree_height_dataset = f'NASA/MEASURES/GFCC/TREE_HEIGHT/v1/{gfcc_year}'

            tree_height = ee.Image(tree_height_dataset)
            th_data = tree_height.select('tree_height').reduceRegion(
                reducer=ee.Reducer.mean(),
                geometry=geometry,
                scale=30
            ).get('tree_height').getInfo()

            result['Tree_Height_Meters'] = th_data

            # Add tree height class
            if th_data is not None:
                if th_data < 5:
                    height_class = 'Low vegetation/young forest'
                elif th_data < 15:
                    height_class = 'Medium-height forest'
                else:
                    height_class = 'Tall forest'

                result['Tree_Height_Class'] = height_class
        except Exception as e:
            # Tree height data may not be available for all regions
            print(f"Error getting tree height data (possibly no data for this region): {str(e)}")

        # 3. If possible, extract forest change information
        if year > 2000:
            try:
                # Determine the previous available GFCC year
                if gfcc_year == 2005:
                    prev_year = 2000
                elif gfcc_year == 2010:
                    prev_year = 2005
                elif gfcc_year == 2015:
                    prev_year = 2010
                else:
                    prev_year = None

                if prev_year:
                    # Build forest change dataset
                    gfcc_tcc_dataset = f'NASA/MEASURES/GFCC/TCC/v3/{prev_year}_{gfcc_year}'

                    tree_change = ee.Image(gfcc_tcc_dataset)
                    tcc_data = tree_change.select('tree_canopy_cover_change').reduceRegion(
                        reducer=ee.Reducer.mean(),
                        geometry=geometry,
                        scale=30
                    ).get('tree_canopy_cover_change').getInfo()

                    result['Tree_Cover_Change_Percent'] = tcc_data

                    # Add change class
                    if tcc_data is not None:
                        if tcc_data < -15:
                            change_class = 'Significant loss'
                        elif tcc_data < -5:
                            change_class = 'Moderate loss'
                        elif tcc_data <= 5:
                            change_class = 'Stable'
                        elif tcc_data < 15:
                            change_class = 'Moderate gain'
                        else:
                            change_class = 'Significant gain'

                        result['Forest_Change_Class'] = change_class
            except Exception as e:
                print(f"Error getting forest change data: {str(e)}")

    except Exception as e:
        print(f"Error getting NASA GFCC forest data: {str(e)}")

    return result

# 5. Hansen Global Forest Change (30m, 2000-present)
def get_hansen_forest(geometry, year):
    """
    Get Hansen Global Forest Change data.
    Baseline year: 2000
    Latest year: 2022
    Resolution: 30m
    """
    result = {
        'Hansen_Tree_Cover_2000_Percent': None,
        'Hansen_Forest_Class': None,
        'Hansen_Forest_Loss_Year': None,
        'Hansen_Forest_Gain': None
    }

    try:
        # Hansen data includes a 2000 baseline cover and changes from 2000-2022
        # Only process if the year is within the valid range
        if year < 2000:
            return result

        # Limit the year to the maximum available data year
        valid_year = min(year, 2022)

        # Get Hansen dataset
        hansen = ee.Image('UMD/hansen/global_forest_change_2022_v1_10')

        # 1. Extract tree cover for the year 2000
        treecover2000 = hansen.select('treecover2000').reduceRegion(
            reducer=ee.Reducer.mean(),
            geometry=geometry,
            scale=30
        ).get('treecover2000').getInfo()

        result['Hansen_Tree_Cover_2000_Percent'] = treecover2000

        # Add forest cover class
        if treecover2000 is not None:
            if treecover2000 < 10:
                forest_class = 'Non-forest'
            elif treecover2000 < 30:
                forest_class = 'Sparse forest'
            elif treecover2000 < 60:
                forest_class = 'Moderate forest'
            else:
                forest_class = 'Dense forest'

            result['Hansen_Forest_Class'] = forest_class

        # 2. Check for forest loss and the year of loss
        # Note: lossyear is 0-22, representing 2000-2022
        if valid_year > 2000:
            # Create a mask to only consider loss up to the specified year
            year_offset = valid_year - 2000
            loss_mask = hansen.select('lossyear').lte(year_offset).And(hansen.select('lossyear').gt(0))

            # Check if there was any loss
            has_loss = loss_mask.reduceRegion(
                reducer=ee.Reducer.anyNonZero(),
                geometry=geometry,
                scale=30
            ).get('lossyear').getInfo()

            if has_loss:
                # Extract the year of loss
                loss_year = hansen.select('lossyear').updateMask(loss_mask).reduceRegion(
                    reducer=ee.Reducer.min(),  # Get the earliest loss year
                    geometry=geometry,
                    scale=30
                ).get('lossyear').getInfo()

                if loss_year is not None and loss_year > 0:
                    result['Hansen_Forest_Loss_Year'] = 2000 + loss_year

        # 3. Check for forest gain (during 2000-2012 period)
        if valid_year >= 2012:  # Gain data is only for the 2000-2012 period
            gain = hansen.select('gain').reduceRegion(
                reducer=ee.Reducer.anyNonZero(),
                geometry=geometry,
                scale=30
            ).get('gain').getInfo()

            result['Hansen_Forest_Gain'] = bool(gain) if gain is not None else None

    except Exception as e:
        print(f"Error getting Hansen forest data: {str(e)}")

    return result

# 6. JAXA ALOS PALSAR Forest/Non-Forest (25m, 2007-2020)
def get_jaxa_forest(geometry, year):
    """
    Get JAXA ALOS PALSAR forest/non-forest data.
    Available years: 2007-2010, 2015-2020
    Resolution: 25m
    """
    result = {
        'JAXA_Forest_Year': None,
        'JAXA_Forest_Class': None,
        'JAXA_Forest_Percent': None
    }

    try:
        # Determine the closest available year
        available_years = [2007, 2008, 2009, 2010, 2015, 2016, 2017, 2018, 2019, 2020]

        # If outside the available year range, return an empty result
        if year < min(available_years) or year > max(available_years):
            return result

        # Find the closest year
        closest_year = min(available_years, key=lambda x: abs(x - year))
        result['JAXA_Forest_Year'] = closest_year

        # Build the dataset ID
        dataset_id = f'JAXA/ALOS/PALSAR/YEARLY/FNF{closest_year}'
        jaxa_fnf = ee.Image(dataset_id)

        # Extract forest/non-forest classification
        # 1: Forest, 2: Non-forest, 3: Water
        fnf_value = jaxa_fnf.select('fnf').reduceRegion(
            reducer=ee.Reducer.mode(),
            geometry=geometry,
            scale=25
        ).get('fnf').getInfo()

        # Define classifications
        fnf_classes = {
            1: 'Forest',
            2: 'Non-forest',
            3: 'Water'
        }

        if fnf_value is not None:
            result['JAXA_Forest_Class'] = fnf_classes.get(fnf_value, 'Unknown')

            # If buffered, calculate forest percentage
            if isinstance(geometry, ee.Geometry.Polygon):
                forest_mask = jaxa_fnf.select('fnf').eq(1)
                forest_area = forest_mask.reduceRegion(
                    reducer=ee.Reducer.sum(),
                    geometry=geometry,
                    scale=25
                ).get('fnf').getInfo()

                total_pixels = jaxa_fnf.select('fnf').reduceRegion(
                    reducer=ee.Reducer.count(),
                    geometry=geometry,
                    scale=25
                ).get('fnf').getInfo()

                if forest_area is not None and total_pixels and total_pixels > 0:
                    forest_percent = (forest_area / total_pixels) * 100
                    result['JAXA_Forest_Percent'] = forest_percent

    except Exception as e:
        print(f"Error getting JAXA ALOS PALSAR forest data: {str(e)}")

    return result

# 7. Dynamic World (10m, 2015-present)
def get_dynamic_world(geometry, year):
    """
    Get Dynamic World near real-time land cover data.
    Available years: 2015-present
    Resolution: 10m
    """
    result = {
        'DW_Land_Class': None,
        'DW_Land_Class_Name': None,
        'DW_Year': None,
        'DW_Tree_Probability': None,
        'DW_Veg_Probability': None
    }

    # Dynamic World classifications
    dw_classes = {
        0: 'Water',
        1: 'Trees',
        2: 'Grass',
        3: 'Flooded vegetation',
        4: 'Crops',
        5: 'Shrub & scrub',
        6: 'Built area',
        7: 'Bare ground',
        8: 'Snow & ice'
    }

    try:
        # Dynamic World starts in 2015
        if year < 2015:
            return result

        # Limit to the latest year
        valid_year = min(year, 2023)
        result['DW_Year'] = valid_year

        # Create date range
        start_date = ee.Date.fromYMD(valid_year, 1, 1)
        end_date = ee.Date.fromYMD(valid_year, 12, 31)

        # Get Dynamic World data
        dw = ee.ImageCollection('GOOGLE/DYNAMICWORLD/V1') \
            .filterDate(start_date, end_date) \
            .filterBounds(geometry)

        # Check if data is available
        if dw.size().getInfo() > 0:
            # Calculate annual average probability for each class
            probabilities = dw.select('label').reduce(ee.Reducer.mode())
            tree_prob = dw.select('trees').mean()
            veg_prob = tree_prob.add(dw.select(['grass', 'shrub_and_scrub', 'crops']).mean())

            # Extract major land cover class
            label = probabilities.reduceRegion(
                reducer=ee.Reducer.mode(),
                geometry=geometry,
                scale=10
            ).get('label_mode').getInfo()

            if label is not None:
                result['DW_Land_Class'] = label
                result['DW_Land_Class_Name'] = dw_classes.get(label, 'Unknown')

            # Extract tree and vegetation probabilities
            tree_probability = tree_prob.reduceRegion(
                reducer=ee.Reducer.mean(),
                geometry=geometry,
                scale=10
            ).get('trees').getInfo()

            veg_probability = veg_prob.reduceRegion(
                reducer=ee.Reducer.mean(),
                geometry=geometry,
                scale=10
            ).get('trees').getInfo()

            result['DW_Tree_Probability'] = tree_probability
            result['DW_Veg_Probability'] = veg_probability

    except Exception as e:
        print(f"Error getting Dynamic World data: {str(e)}")

    return result

# Function to integrate all data sources
def get_landcover_and_forest_data(row, buffer_size=None):
    """Get land cover and forest data from all available sources"""
    try:
        # Prepare date and location data
        event_date = pd.to_datetime(row[config.DATE_COLUMN]) if pd.notna(row[config.DATE_COLUMN]) else None
        if event_date is None:
            print(f"Row {row[config.ID_COLUMN]} has no valid date")
            return None

        lat = row[config.LAT_COLUMN]
        lon = row[config.LON_COLUMN]

        # Validate coordinates
        if not (-90 <= lat <= 90) or not (-180 <= lon <= 180):
            print(f"Invalid coordinates: Lat={lat}, Lon={lon}")
            return None

        # Get the year
        year = event_date.year

        # Create point geometry or buffered point
        geometry = create_buffered_point(lon, lat, buffer_size)

        # Initialize results dictionary
        result = {
            config.ID_COLUMN: row[config.ID_COLUMN],
            'Event_Date': event_date,
            'Event_Year': year,
            'Latitude': lat,
            'Longitude': lon,
            'Buffer_Size_Meters': buffer_size
        }

        # Add other columns from the original data
        for col in row.index:
            if col not in [config.ID_COLUMN, config.DATE_COLUMN, config.LAT_COLUMN, config.LON_COLUMN]:
                result[col] = row[col]

        # Get land cover and forest data from various sources

        # 1. ESA WorldCover (10m, 2020+)
        esa_data = get_esa_worldcover(geometry, year)
        result.update(esa_data)

        # 2. MODIS Land Cover (500m, 2001+)
        modis_data = get_modis_landcover(geometry, year)
        result.update(modis_data)

        # 3. Copernicus Global Land Cover (100m, 2015+)
        copernicus_data = get_copernicus_landcover(geometry, year)
        result.update(copernicus_data)

        # 4. NASA GFCC (30m, 2000/2005/2010/2015)
        gfcc_data = get_nasa_gfcc(geometry, year)
        result.update(gfcc_data)

        # 5. Hansen Global Forest Change (30m, 2000+)
        hansen_data = get_hansen_forest(geometry, year)
        result.update(hansen_data)

        # 6. JAXA ALOS PALSAR Forest/Non-Forest (25m, 2007-2020)
        jaxa_data = get_jaxa_forest(geometry, year)
        result.update(jaxa_data)

        # 7. Dynamic World (10m, 2015+)
        dw_data = get_dynamic_world(geometry, year)
        result.update(dw_data)

        return result

    except Exception as e:
        print(f"Error processing ID {row.get(config.ID_COLUMN, 'unknown')}: {str(e)}")
        import traceback
        print(traceback.format_exc())
        return None

# Main processing function
def process_landcover_data():
    """Process landslide data to extract land cover and forest data for each point"""
    # Initialize Earth Engine and mount Google Drive
    initialize_gee()
    mount_drive()

    # Ensure the output directory exists
    output_path = ensure_output_dir()
    print(f"Output file will be saved to: {output_path}")

    # Read landslide data
    try:
        landslides = pd.read_csv(config.INPUT_FILE)
        print(f"Successfully read {len(landslides)} landslide records")

        # Ensure the date column is in datetime format
        landslides[config.DATE_COLUMN] = pd.to_datetime(landslides[config.DATE_COLUMN], errors='coerce')

        # Remove records with no date
        landslides_with_dates = landslides.dropna(subset=[config.DATE_COLUMN])
        if len(landslides) > len(landslides_with_dates):
            print(f"Warning: Removed {len(landslides) - len(landslides_with_dates)} records with no valid date")
            landslides = landslides_with_dates
    except Exception as e:
        print(f"Error reading landslide data: {str(e)}")
        return

    # Get the ID of the last processed record
    last_processed_id = get_checkpoint()
    print(f"Starting processing from ID {last_processed_id}")

    # Filter for unprocessed data
    landslides_to_process = landslides[landslides[config.ID_COLUMN] > last_processed_id]

    if len(landslides_to_process) == 0:
        print("No new data to process")
        return

    print(f"Need to process {len(landslides_to_process)} records")

    # Process each landslide record
    results = []
    error_count = 0

    for idx, row in tqdm(landslides_to_process.iterrows(), total=len(landslides_to_process), desc="Processing landslide data"):
        try:
            # Get land cover and forest data using a buffer
            result = get_landcover_and_forest_data(row, buffer_size=config.BUFFER_SIZE)

            if result is not None:
                # Add to the results list
                results.append(result)

                # Update the checkpoint
                update_checkpoint(row[config.ID_COLUMN])

                # Periodically save results
                if len(results) % 10 == 0:
                    temp_df = pd.DataFrame(results)
                    temp_df.to_csv(output_path, mode='a', header=not os.path.exists(output_path), index=False)
                    print(f"Saved intermediate results, currently at ID: {row[config.ID_COLUMN]}")
                    results = []  # Clear saved results

        except Exception as e:
            print(f"Error processing ID {row[config.ID_COLUMN]}: {str(e)}")
            error_count += 1

            # If there are too many errors, it might be an API issue, so pause
            if error_count > 5:
                print("Too many errors, pausing for 30 seconds...")
                time.sleep(30)
                error_count = 0

        # Short sleep to avoid API limits
        time.sleep(config.SLEEP_TIME)

    # Save remaining results
    if results:
        temp_df = pd.DataFrame(results)
        temp_df.to_csv(output_path, mode='a', header=not os.path.exists(output_path), index=False)
        print(f"Saved final results, {len(results)} records in total")

    # Read the complete results and generate a summary
    if os.path.exists(output_path):
        try:
            full_df = pd.read_csv(output_path)
            print(f"Successfully read {len(full_df)} records to generate summary statistics")

            # Generate results summary
            print("\nData Statistical Summary:")

            # Calculate availability rate for each data source
            total_records = len(full_df)

            print(f"Total records: {total_records}")
            print("\nData Source Availability Rate:")

            availability = {
                'ESA WorldCover': full_df['ESA_WorldCover'].notna().sum() / total_records * 100,
                'MODIS Land Cover': full_df['MODIS_IGBP'].notna().sum() / total_records * 100,
                'Copernicus Land Cover': full_df['Copernicus_LC'].notna().sum() / total_records * 100,
                'NASA GFCC': full_df['Tree_Canopy_Cover_Percent'].notna().sum() / total_records * 100,
                'Hansen Forest': full_df['Hansen_Tree_Cover_2000_Percent'].notna().sum() / total_records * 100,
                'JAXA Forest': full_df['JAXA_Forest_Class'].notna().sum() / total_records * 100,
                'Dynamic World': full_df['DW_Land_Class'].notna().sum() / total_records * 100
            }

            for source, avail in availability.items():
                print(f"{source}: {avail:.1f}%")

            # Calculate distribution of land cover/forest types for each source
            print("\nLand Cover Type Distribution (MODIS IGBP):")
            if 'MODIS_IGBP_Class' in full_df.columns:
                modis_dist = full_df['MODIS_IGBP_Class'].value_counts(dropna=True)
                for cls, count in modis_dist.items():
                    print(f"{cls}: {count} ({count/total_records*100:.1f}%)")

            print("\nForest Density Distribution (NASA GFCC):")
            if 'Forest_Density_Class' in full_df.columns:
                forest_dist = full_df['Forest_Density_Class'].value_counts(dropna=True)
                for cls, count in forest_dist.items():
                    print(f"{cls}: {count} ({count/total_records*100:.1f}%)")

            print("\nCompleted land cover and forest data extraction")

            return full_df

        except Exception as e:
            print(f"Error generating statistical summary: {str(e)}")
    else:
        print("No data file found to analyze")

# Main program
if __name__ == "__main__":
    full_data = process_landcover_data()